CWE15_External_Control_of_System_or_Configuration_Setting__w32_51a.c
LISTEN_PORT
LISTEN_BACKLOG
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_51b_badSink(char *data)
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_51_bad.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_51_bad()
References LISTEN_PORT, LISTEN_BACKLOG, CWE15_External_Control_of_System_or_Configuration_Setting__w32_51b_badSink.
Referenced by main.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_51b_goodG2BSink(char *data)
Referenced by goodG2B.
static void goodG2B()
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_51b_goodG2BSink.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_51_good.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_51_good()
References goodG2B.
Referenced by main.