CWE15_External_Control_of_System_or_Configuration_Setting__w32_22b.c
LISTEN_PORT
LISTEN_BACKLOG
int CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badGlobal
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_bad, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badSource.
int CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Global
Referenced by goodG2B1, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Source.
int CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Global
Referenced by goodG2B2, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Source.
char* CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badSource(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badGlobal, LISTEN_PORT, LISTEN_BACKLOG.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_bad.
char* CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Source(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Global.
Referenced by goodG2B1.
char* CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Source(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Global.
Referenced by goodG2B2.