CWE15_External_Control_of_System_or_Configuration_Setting__w32_54a.c
LISTEN_PORT
LISTEN_BACKLOG
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_badSink(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_54c_badSink.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_54_bad.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54_bad()
References LISTEN_PORT, LISTEN_BACKLOG, CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_badSink.
Referenced by main.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_goodG2BSink(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_54c_goodG2BSink.
Referenced by goodG2B.
static void goodG2B()
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_goodG2BSink.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_54_good.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54_good()
References goodG2B.
Referenced by main.