CWE15_External_Control_of_System_or_Configuration_Setting__w32_22a.c
int CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badGlobal
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_bad, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badSource.
int CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Global
Referenced by goodG2B1, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Source.
int CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Global
Referenced by goodG2B2, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Source.
char* CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badSource(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badGlobal, LISTEN_PORT, LISTEN_BACKLOG.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_bad.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_bad()
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badGlobal, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_badSource.
Referenced by main.
char* CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Source(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Global.
Referenced by goodG2B1.
static void goodG2B1()
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Global, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B1Source.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_good.
char* CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Source(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Global.
Referenced by goodG2B2.
static void goodG2B2()
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Global, CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_goodG2B2Source.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_good.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_22_good()
References goodG2B1, goodG2B2.
Referenced by main.