CWE15_External_Control_of_System_or_Configuration_Setting__w32_52b.c
LISTEN_PORT
LISTEN_BACKLOG
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_52c_badSink(char *data)
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_52b_badSink.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_52b_badSink(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_52c_badSink.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_52_bad.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_52c_goodG2BSink(char *data)
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_52b_goodG2BSink.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_52b_goodG2BSink(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_52c_goodG2BSink.
Referenced by goodG2B.