CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b.c
LISTEN_PORT
LISTEN_BACKLOG
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54c_badSink(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_54d_badSink.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_badSink.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_badSink(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_54c_badSink.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_54_bad.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54c_goodG2BSink(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_54d_goodG2BSink.
Referenced by CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_goodG2BSink.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_goodG2BSink(char *data)
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_54c_goodG2BSink.
Referenced by goodG2B.