CWE15_External_Control_of_System_or_Configuration_Setting__w32_74
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_74::badSink(map< int, char *> dataMap)
Referenced by bad.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_74::bad()
References LISTEN_PORT, LISTEN_BACKLOG, badSink.
Referenced by main.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_74::goodG2BSink(map< int, char *> dataMap)
Referenced by goodG2B.
static void CWE15_External_Control_of_System_or_Configuration_Setting__w32_74::goodG2B()
References goodG2BSink.
Referenced by good.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_74::good()
References goodG2B.
Referenced by main.