CWE15_External_Control_of_System_or_Configuration_Setting__w32_82
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_82::bad()
References LISTEN_PORT, LISTEN_BACKLOG, CWE15_External_Control_of_System_or_Configuration_Setting__w32_82::CWE15_External_Control_of_System_or_Configuration_Setting__w32_82_base::action.
Referenced by main.
static void CWE15_External_Control_of_System_or_Configuration_Setting__w32_82::goodG2B()
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_82::CWE15_External_Control_of_System_or_Configuration_Setting__w32_82_base::action.
Referenced by good.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_82::good()
References goodG2B.
Referenced by main.