CWE15_External_Control_of_System_or_Configuration_Setting__w32_81
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_81::bad()
References LISTEN_PORT, LISTEN_BACKLOG, CWE15_External_Control_of_System_or_Configuration_Setting__w32_81::CWE15_External_Control_of_System_or_Configuration_Setting__w32_81_base::action.
Referenced by main.
static void CWE15_External_Control_of_System_or_Configuration_Setting__w32_81::goodG2B()
References CWE15_External_Control_of_System_or_Configuration_Setting__w32_81::CWE15_External_Control_of_System_or_Configuration_Setting__w32_81_base::action.
Referenced by good.
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_81::good()
References goodG2B.
Referenced by main.